image: cypress/browsers:22.15.0

pipelines:
  default:
    - step:
        name: Install dependencies
        script:
          - corepack enable
          - corepack prepare yarn@4.10.3 --activate
          - yarn --version
          - yarn install --immutable

    - step:
        name: Build Vite app
        script:
          - corepack enable
          - corepack prepare yarn@4.10.3 --activate
          - yarn build
        artifacts:
          - dist/**

    - step:
        name: Run Cypress E2E Tests
        script:
          - corepack enable
          - corepack prepare yarn@4.10.3 --activate

          # Start Vite dev server in background
          - yarn dev &

          # Wait for it to be ready
          - yarn wait-on http://localhost:5173

          # Run Cypress headless tests
          - yarn cypress run --browser chrome
