image: cypress/browsers:22.15.0

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - yarn
        script:
          - corepack enable
          - corepack prepare yarn@4.10.3 --activate
          - yarn install --immutable
        artifacts:
          - .yarn/**
          - node_modules/**
          - .pnp.cjs
          - .pnp.loader.mjs

    - step:
        name: Build Vite app
        caches:
          - yarn
        script:
          - corepack enable
          - corepack prepare yarn@4.10.3 --activate
          - yarn build
        artifacts:
          - dist/**

    - step:
        name: Run Cypress E2E Tests
        caches:
          - yarn
        script:
          - corepack enable
          - corepack prepare yarn@4.10.3 --activate

          - yarn dev &
          - yarn wait-on http://localhost:5173

          - yarn cypress run --browser chrome

definitions:
  caches:
    yarn: .yarn/cache